### ISSUE TITLE
Better use less copyrighed pictures

### ISSUE THREAD

**Issue by mathieumd** [PnEcrins/Trombi#4]
Nice project!

I just wanted to friendly warn about the usage of heavily copyrighed pictures in your screenshots. Of course having screenshots is great (and certainly required, anyway), but D*sney or Shūe*sha's lawers may not appreciate this usage.

Maybe using https://thispersondoesnotexist.com/ could be appropriate? I'm not sure about the license, though. You better ask the author. ([but I guess it should be OK](https://www.wired.com/story/github-commercial-ai-tool-built-open-source-code/))

Keep up the good work!

**Comment by mathieumd** [comment]
Ah, désolé, je crois que j'ai trop l'habitude de faire des rapport de bug directement en (mauvais) anglais ! Je peux traduire si besoin.

**Comment by camillemonchicourt** [comment]
Merci pour le retour.
Bien vu. En effet on a fait ça vite fait à la fin du projet pour avoir un aperçu mais on va remplacer pour pas avoir de soucis.
Merci.

**Comment by camillemonchicourt** [comment]
Fait dans la 1.2.0. merci.
